name: hierslam
channels:
  - pytorch
  - nvidia/label/cuda-11.6.0
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - numpy=1.26.4
  - scipy=1.13.0
  - pillow=10.3.0
  - pandas=2.2.2
  - matplotlib=3.8.4
  - scikit-learn=1.4.2
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6.2
  - pip=24.0
  - pip:
      - addict==2.4.0
      - opencv-python==4.9.0.80
      - imageio==2.34.1
      - jupyterlab-widgets==3.0.10
      - plotly==5.22.0
      - tqdm==4.65.0
      - wandb==0.17.0